#!/usr/bin/env python3
"""Convert a binary file into a C header holding a PROGMEM byte array.

Usage:  python tools/bin2header.py <input file> <output .h> <ARRAY_NAME>

Example (regenerate the embedded web-page background):
    python tools/bin2header.py assets/images/RotorHazard-Logo-416x487.png firmware/RaceCounter/bg_png.h BG_PNG
"""
import os
import sys


def main():
    if len(sys.argv) != 4:
        sys.exit(__doc__)
    src, dst, name = sys.argv[1:]
    data = open(src, "rb").read()

    lines = [
        f"// Generated by tools/bin2header.py from {os.path.basename(src)} ({len(data)} bytes). Do not edit by hand.",
        "#pragma once",
        "#include <pgmspace.h>",
        "",
        f"const uint8_t {name}[] PROGMEM = {{",
    ]
    for i in range(0, len(data), 16):
        lines.append("    " + ", ".join(f"0x{b:02X}" for b in data[i:i + 16]) + ",")
    lines += [
        "};",
        f"const size_t {name}_LEN = sizeof({name});",
        "",
    ]
    with open(dst, "w", newline="\n") as f:
        f.write("\n".join(lines))
    print(f"{dst}: {len(data)} bytes as {name}[]")


if __name__ == "__main__":
    main()
