#!/usr/bin/env python3
"""Convert a TrueType font into an Adafruit GFX font header (the format Seeed_GFX / TFT_eSPI free fonts use).

Usage:  python tools/ttf2gfx.py <font.ttf> <point size> <output .h> [first char] [last char]

The point size is interpreted the way Adafruit's fontconvert does (141 dpi), so the result matches a header
made with that tool. The character range defaults to the printable ASCII set (0x20..0x7E).

Example:
    python tools/ttf2gfx.py assets/fonts/Orbitron-Bold.ttf 30 firmware/RaceCounter/OrbitronBold30pt7b.h
"""
import os
import re
import sys

from PIL import Image, ImageDraw, ImageFont

DPI = 141


def main():
    if len(sys.argv) not in (4, 6):
        sys.exit(__doc__)
    src, size, dst = sys.argv[1], int(sys.argv[2]), sys.argv[3]
    first, last = (int(sys.argv[4], 0), int(sys.argv[5], 0)) if len(sys.argv) == 6 else (0x20, 0x7E)

    px = round(size * DPI / 72)                         # em size in pixels
    font = ImageFont.truetype(src, px)
    ascent = font.getmetrics()[0]
    name = re.sub(r"[^A-Za-z0-9]", "", os.path.splitext(os.path.basename(src))[0]) + f"{size}pt7b"

    bitmaps, glyphs, bits = [], [], []
    for code in range(first, last + 1):
        ch = chr(code)
        img = Image.new("L", (3 * px, 3 * px), 0)        # drawn with the origin at (px, 0): the ascender line
        ImageDraw.Draw(img).text((px, 0), ch, font=font, fill=255)
        img = img.point(lambda v: 255 if v >= 128 else 0)
        box = img.getbbox()                             # the ink box (None for a blank glyph such as space)
        if box:
            x0, y0, x1, y1 = box
            w, h = x1 - x0, y1 - y0
            glyph_bits = [1 if img.getpixel((x, y)) else 0 for y in range(y0, y1) for x in range(x0, x1)]
            x0 -= px
        else:
            x0 = y0 = w = h = 0
            glyph_bits = []
        glyphs.append((len(bits) // 8, w, h, round(font.getlength(ch)), x0, y0 - ascent, ch))
        bits.extend(glyph_bits)
        while len(bits) % 8:                            # (glyphs start on a byte boundary, as fontconvert does)
            bits.append(0)

    data = bytes(int("".join(map(str, bits[i:i + 8])), 2) for i in range(0, len(bits), 8))

    lines = [f"// Generated by tools/ttf2gfx.py from {os.path.basename(src)} at {size} pt. Do not edit by hand.",
             "#pragma once", "",
             f"const uint8_t {name}Bitmaps[] PROGMEM = {{"]
    for i in range(0, len(data), 12):
        lines.append("  " + ", ".join(f"0x{b:02X}" for b in data[i:i + 12]) + ",")
    lines += ["};", "", f"const GFXglyph {name}Glyphs[] PROGMEM = {{"]
    for off, w, h, adv, xo, yo, ch in glyphs:
        lines.append(f"  {{ {off:6d}, {w:3d}, {h:3d}, {adv:3d}, {xo:4d}, {yo:5d} }},   // 0x{ord(ch):02X} '{ch}'")
    lines += ["};", "",
              f"const GFXfont {name} PROGMEM = {{",
              f"  (uint8_t  *){name}Bitmaps,",
              f"  (GFXglyph *){name}Glyphs,",
              f"  0x{first:02X}, 0x{last:02X}, {px} }};", ""]
    with open(dst, "w", newline="\n") as f:
        f.write("\n".join(lines))
    print(f"{dst}: {name}, {len(glyphs)} glyphs, {len(data)} bytes of bitmap")


if __name__ == "__main__":
    main()
